### ISSUE TITLE
myip breaks if network interface is not en0

### ISSUE THREAD

**Issue by switchswap** [austintraver/homebrew-tap#1]
My laptop uses en1 as it's wireless interface so this script returns a blank line for my private IP address. 

I think it's because the code is searching for the en0 interface.

**Comment by austintraver** [comment]
Thank you for bringing this to my attention @switchswap ❤️ , fixed in https://github.com/austintraver/homebrew-tap/commit/593421b69cf12bf4c4dc6abe20f5d5e8061af8b1
